language: php

php:
  - "7.2"

before_script:
  - cp .env.travis .env
  - mysql -e 'create database tutuka_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
