language: php

php:
  - "7.2"

services:
  - mysql

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  
before_install:
  - mysql -e 'CREATE DATABASE homestead_test;'

script:
  - vendor/bin/phpunit
  - vendor/bin/behat
